channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ipython=8.18.1
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jupyterlab_widgets=3.0.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.3.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - python=3.9.18
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - typing_extensions=4.11.0
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - docker-pycreds==0.4.0
      - easyprocess==1.1
      - einops==0.8.0
      - entrypoint2==1.1
      - filelock==3.14.0
      - fonttools==4.51.0
      - fsspec==2024.5.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - huggingface-hub==0.23.0
      - idna==3.7
      - imbalanced-learn==0.12.0
      - importlib-metadata==7.0.1
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - jinja2==3.1.4
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - liac-arff==2.5.0
      - linformer==0.2.3
      - loguru==0.7.2
      - mamba-ssm==1.2.0.post1
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.6
      - minio==7.2.3
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openml==0.14.1
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.3
      - patool==1.15.0
      - pillow==10.3.0
      - platformdirs==4.1.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==14.0.2
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyunpack==0.3
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - regex==2024.5.15
      - requests==2.31.0
      - safetensors==0.4.3
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.12
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==1.13.1
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.1
      - transformers==4.41.0
      - triton==2.3.0
      - tzdata==2024.1
      - urllib3==1.26.18
      - wandb==0.17.0
      - xmltodict==0.13.0
      - zipp==3.17.0
